config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/transacts/new', to: 'transacts#new'
  # get '/transacts/:id', to: 'transacts#show', as: 'transact'
  # get '/transacts', to: 'transacts#index'
  # post '/transacts', to: 'transacts#create'

  resources :transacts
  resources :traders, only: [:show, :index]
  resources :salespeople, only: [:show, :index]
  resources :clients, only: [:show, :index]
  resources :bonds, only: [:show, :index]
  resources :users, only: [:new, :create, :update]

  get '/home', to: 'users#home', as: 'home'
  get 'signup', to: 'users#new'

  get '/auth/github/callback' => 'sessions#create'

  get '/users/new_fb', to: 'users#new_fb'

  patch '/transacts/:id/confirm', to: 'transacts#confirm', as: 'confirm_transact'
  get '/pending_transacts', to: 'transacts#pending'

  get '/signin', to: 'sessions#new', as: 'signin'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions/', to: 'sessions#destroy'

  root 'users#home'

  resources :traders, only: [:show] do
  	resources :transacts, only: [:show, :index]
    resources :bonds, only: [:index]
    get '/pending_transacts', to: 'transacts#pending'
  end

  resources :clients, only: [:show] do
    resources :transacts, only: [:show, :index, :new, :create]
  end

  resources :bonds, only: [:show] do
    resources :transacts, only: [:show, :index, :new, :create]
  end

  resources :salespeople, only: [:show] do
    resources :transacts, only: [:show, :index]
    get '/pending_transacts', to: 'transacts#pending'
  end

end

app/models/transact.rb
class Transact < ApplicationRecord
	belongs_to :bond
	belongs_to :client
	belongs_to :trader
	has_many :salesperson_transacts
	has_many :salespeople, through: :salesperson_transacts

	validates_inclusion_of :we_buy, in: [true, false]
	validates_presence_of :size, :price, :bond_id, :client_id, :trader_id, :trade_time
	validate :in_past

	validates :size, :price, :numericality => {greater_than: 0}

	def in_past
	    if trade_time.present? && trade_time >= Time.zone.now
	      errors.add(:trade_time, "Trade time must be in the past")
	    end
  	end

	def trade_type
		if self.we_buy
			"Buy"
		else
			"Sell"
		end
	end

	def next_id
	  self.class.not_pending.where("trade_time > ?", trade_time).order("trade_time ASC").first.try(:id)
	end

	def bond_yield
		Bondie::Issue.new(coupon: self.bond.coupon / 100, maturity_date: self.bond.maturity, coupon_frequency: 2).ytm(self.trade_time.to_date, price: self.price)
	end

	def self.total_volume
		sum("size")
	end

	def self.last_month
		where("trade_time >?", Time.now - 1.months)
	end

	def self.last_quarter
		where("trade_time >?", Time.now - 3.months)
	end

	def self.most_active_by_volume
		group(:bond_id).order('sum_size DESC').sum(:size)
	end

	def self.most_active_by_trades
		group(:bond_id).order('count_id desc').count('id')
	end

	def self.top_clients_by_volume
		group(:client_id).order('sum_size DESC').sum(:size)
	end

	def self.top_clients_by_volume
		group(:client_id).order('sum_size DESC').sum(:size)
	end

	def self.top_traders
		group(:trader_id).order('sum_size DESC').sum(:size)
	end

	def self.top_salespeople
		joins(:salesperson_transacts).group(:salesperson_id).order('sum_size DESC').sum(:size)
	end

	def self.not_pending
		where(pending: false)
	end

	def self.pending
		where(pending: true)
	end

	def self.date_sorted
		order(trade_time: :desc)
	end
	
end

app/controllers/transacts_controller.rb
class TransactsController < ApplicationController

	before_action :current_transact, only: [:show, :edit, :update, :confirm, :destroy]
  # include Bondie::Issue

  def new
    if params[:bond_id]
      @bond = Bond.find_by(id: params[:bond_id])
    elsif params[:client_id]
      @client = Client.find_by(id: params[:client_id])
    end
  	@transact = Transact.new
  end

  def create
    @transact = Transact.new(transact_params)
    if @transact.valid?
      @transact.save
			if params[:no_reload]
				render json: @transact, status: 201
      else
        redirect_to transact_path(@transact)
      end
    else
      render :new
    end
  end

  def show
    @next_id = @transact.next_id
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @transact}
    end
  end

  def confirm
    if user_is_trader
      @transact.update(pending: false)
    end
    redirect_to transact_path(@transact)
  end

  def index
    @transacts = get_period_transacts

    if params[:trader_id]
      @entity = Trader.find(params[:trader_id])
      @transacts = @transacts.where(trader_id: params[:trader_id])
    elsif params[:bond_id]
      @bond = Bond.find(params[:bond_id])
      @transacts = @transacts.where(bond_id: params[:bond_id])
			respond_to do |format|
			format.html {
				render :index}
			format.json {
				@transacts = @transacts.last_month.date_sorted.limit(5)
				render json: @transacts }
			end
    elsif params[:client_id]
      @entity = Client.find(params[:client_id])
      @transacts = @transacts.where(client_id: params[:client_id])
      respond_to do |format|
        format.html {
          render :index}
        format.json {
          @transacts = @transacts.date_sorted.limit(5)
          render json: @transacts}
      end
    elsif params[:salesperson_id]
      @entity = Salesperson.find(params[:salesperson_id])
      @transacts = @transacts.joins(:salesperson_transacts).where(salesperson_transacts: {salesperson_id: params[:salesperson_id]})
    end

    @transacts = @transacts.date_sorted

  end

  def pending
    if params[:trader_id]
      @transacts = Transact.where(trader_id: params[:trader_id]).pending
    elsif params[:salesperson_id]
      @transacts = Salesperson.find_by(id: params[:salesperson_id]).transacts.pending
    else
      @transacts = Transact.pending
    end
  end

  def edit
    if !user_is_trader
      redirect_to transact_path(@transact)
    end
  end

  def update
  	@transact.update(transact_params)
  	redirect_to transact_path(@transact)
  end

  def destroy
    if user_is_trader || @transact.pending == true
      @transact.destroy
    end
    redirect_to transacts_path
  end


  private

  def transact_params
    params.require(:transact).permit(
       :we_buy,
       :size,
       :price,
       :bond_id,
       :client_id,
       :trader_id,
       :trade_time,
       :pending,
       salesperson_ids:[]
      )
  end

  def current_transact
  	@transact = Transact.find_by(id: params[:id])
  end

  def get_period_transacts
    if params[:period] == "one_month"
      Transact.not_pending.last_month
    elsif params[:period] == "one_quarter"
      Transact.not_pending.last_quarter
    else
      Transact.not_pending
    end
  end


end

app/views/transacts/_form.html.erb
<% if @transact.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@transact.errors.count, "error") %>
      prohibited this post from being saved:
    </h2>
 
    <ul>
    <% @transact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for(@transact) do |f| %>
<div class="row">
  <div class="col-sm-3">
    <div class="form-group">
      <%= f.label "Buy" %>
      <%= f.radio_button :we_buy, true %>
      <%= f.label "Sell" %>
      <%= f.radio_button :we_buy, false %>
    </div>

    <div class="form-group">
      <%= f.label "Size (M)" %><br> 
      <%= f.number_field :size, class: "form-control" %>
    </div>
    <% if @bond %>
    <%= f.hidden_field :bond_id, value: @bond.id %>
    <% else %>
       <div class="form-group">
        <%= f.label :bond_id %><br>
        <%= f.collection_select :bond_id, Bond.order(:ticker), :id, :print_description, {}, {class: "form-control"} %>
      </div>
    <% end %>
     <div class="form-group">
      <%= f.label :price %><br>
      <%= f.number_field :price, class: "form-control", step: 0.001 %>
    </div>
  </div>
  <div class="col-sm-3" >   
    <br><br>
     <div class="form-group" style="margin-left: 25px">
      <%= f.label :trader_id %><br>
      <%= f.collection_select :trader_id, Trader.order(:name), :id, :name, {include_blank: true, class: "form-control", selected: select_trader}, {style:"width:150px; height:30px"} %>
     </div>
     <br><br>
      <% if @client %>
        <%= f.hidden_field :client_id, value: @client.id %>
      <% else %>
        <div class="form-group" style="margin-left: 25px">
        <%= f.label :client_id %><br>

        <%= f.collection_select :client_id, Client.order(:name), :id, :name, {include_blank: true, class: "form-control"}, {style:"width:150px; height:30px"} %>
      <% end %>
     </div>
  </div>
<div class="col-sm-3"> 
  <br><br>
   <div class="form-group">
    <%= f.label "Salespeople" %><br>
    <%= f.collection_select :salesperson_ids, Salesperson.order(:name), :id, :name, {include_blank: true, class: "form-control", selected: select_salesperson}, {multiple: true, style:"width:150px; height:100px"} %>
  </div>
   <div class="form-group">
    <%= f.label "Time of trade" %><br>
    <%= datetime_local_field :transact, :trade_time, value: Time.now.strftime("%Y-%m-%dT%H:%M") %>
  </div>
</div>
</div>
  <br>
  <% if user_is_trader %>
    <%= f.hidden_field :pending, value: false %>
  <% else %>
    <%= f.hidden_field :pending, value: true %>  
  <% end %>
  <div class="actions">
    <%= f.submit value: "Book Trade", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/transacts/edit.html.erb
<h3>Edit Trade Details</h3><br>

<%= render 'form' %>

app/views/transacts/index.html.erb
<% if @entity %>
  <h2><%= @entity.name %></h2>
<% elsif @bond %>
  <h2><%= @bond.print_description %></h2>
<% end %>

<table class="table table-striped">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><strong>B/S</strong></td>
      <td><strong>Size</strong></td>
      <% if !params[:bond_id] %>
        <td><strong>Bond</strong></td>
      <% end %>
      <td><strong>Price</strong></td>
      <% if !params[:trader_id] %>
        <td><strong>Trader</strong></td>
      <% end %>
      <% if !params[:client_id] %>
        <td><strong>Client</strong></td>
      <% end %>
      <td><strong>Trade Date</strong></td>
      
    </tr>

    <% @transacts.each do |transact| %>
      <tr>
        <td><%= link_to transact.trade_type, transact_path(transact) %></td>
        <td><%= transact.size.to_s %></td>
        <% if !params[:bond_id] %>
        <td><%= link_to transact.bond.print_description, bond_path(transact.bond) %></td>
        <% end %>
        <td><%= transact.price.to_s %></td>
        <% if !params[:trader_id] %>
        <td><%= link_to transact.trader.name, trader_path(transact.trader) %></td>
        <% end %>
        <% if !params[:client_id] %>
        <td><%= link_to transact.client.name, client_path(transact.client) %></td>
        <% end %>
        <td><%= transact.trade_time.strftime('%m-%d-%y') %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transacts/new.html.erb
<% if @bond %>
  <h3>New <%= @bond.print_description %> Trade</h3>
<% elsif @client %>
	<h3>New <%= @client.name %> Trade</h3>
 <% else %>
  <h3>Book a new trade</h3>
<% end %>
<br>
<%= render 'form' %>

app/views/transacts/pending.html.erb
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <tr> 
      <td><strong>B/S</strong></td>
      <td><strong>Bond</strong></td>
      <td><strong>Size</strong></td>
      <td><strong>Trade Date</strong></td>
      <td><strong>Client</strong></td>
      <% if user_is_trader %>
      <td><strong>Confirm Trade</strong></td>
      <td><strong>Edit Trade</strong></td>
      <% end %>
    </tr>
    <% @transacts.each do |transact| %>
      <tr>
        <td><%= link_to transact.trade_type, transact_path(transact) %></td>
        <td><%= transact.bond.print_description %></td>
        <td><%= transact.size.to_s %></td>
        <td><%= transact.trade_time.strftime('%m-%d-%y') %></td>
        <td><%= transact.client.name %></td>
        <% if user_is_trader %>
        <td><%= link_to "Confirm",confirm_transact_path(transact), method: :patch %></td>
        <td><%= link_to "Edit", edit_transact_path(transact) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/transacts/show.html.erb
<button class="js-next-transact" data-id="<%= @next_id %>">Next Trade</button>
<div class="col-sm-8" id="js-transact-success-message"></div>
<div class="col-sm-8">
<table class="table">
  <thead>
    <tr>
    	<% if @transact.pending %>
    		<th colspan="2">Pending Trade</th>
    	<% else %>
    		<th colspan="2">Completed Trade</th>
    	<% end %>
    </tr>
  </thead>
  <tbody>
  	<tr>
  		<td>Bond</td>
  		<td id="description"><%= @transact.bond.print_description %></td>
  	</tr>
  	<tr>
  		<td>Type</td>
  		<td id="type">
  			<% if @transact.we_buy == true %>
				Buy
			<% else %>
				Sell
			<% end %>
		</td>
  	</tr>
  	<tr>
  		<td>Size (m)</td>
  		<td id="size"><%= @transact.size %></td>
  	</tr>

  	<tr>
  		<td>Price</td>
  		<td id="price"><%= number_to_currency(@transact.price) %></td>
  	</tr>
  	<tr>
  		<td>Trader</td>
  		<td id="trader"><%= @transact.trader.name %></td>
  	</tr>
  	<tr>
  		<td>Client</td>
  		<td id="client"><%= @transact.client.name %></td>
  	</tr>
  	<% if @transact.salespeople.any? %>
  		<tr>
  			<td>Salespeople</td>
  			<td id= "salespeople">
  				<%= @transact.salespeople.map{|sp| sp.name}.join(", ") %>
			</td>
	  	</tr>
  	<% end %>
  	<tr>
  		<td>Trade Time</td>
  		<td id="trade_time"><%= @transact.trade_time.strftime('%m-%d-%Y %H:%M:%S') %></td>
  	</tr>
  	<tr>
  		<td>Created at</td>
  		<td id="created_at"><%= @transact.created_at.strftime('%m-%d-%Y %H:%M:%S') %></td>
  	</tr>
  	<tr>
  		<td>Last Updated</td>
  		<td id="updated_at"><%= @transact.updated_at.strftime('%m-%d-%Y %H:%M:%S') %></td>
  	</tr>
  </tbody>
</table>

<button class="js-new-transact" data-id="<%= @transact.id %>">Duplicate Trade</button>


<% if user_is_trader %>
	<%= link_to "Edit Trade Details", edit_transact_path(@transact), id: "edit"%>
	<% if @transact.pending == true %>
		<%= link_to "Confirm Trade", confirm_transact_path(@transact), method: :patch, id: "confirm" %>
	<% end %>
	<%= link_to "Cancel Trade", transact_path(@transact), method: :delete, id: "cancel" %>
<% end %>
</div>

<div class="col-sm-12" id="duplicate"></div>




<script id="duplicate-transact-template" type="text/x-handlebars-template">
  <br><br>
  <div class="col-sm-4">
  <form class="new_transact" id="new_transact" action="/transacts" accept-charset="UTF-8" method="post">

    <input name="utf8" type="hidden" value="✓">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

    <div class="form-group">
      <label for="transact_Buy">Buy</label>
      <input type="radio" value="true" name="transact[we_buy]" id="transact_we_buy_true"  {{checkType trade_type "Buy"}}>
      <label for="transact_Sell">Sell</label>
      <input type="radio" value="false" name="transact[we_buy]" id="transact_we_buy_false" {{checkType trade_type "Sell"}}>
    </div>

    <div class="form-group">
      <label for="transact_Size (M)">Size (m)</label><br>
      <input class="form-control" type="number" name="transact[size]" id="transact_size" value="{{size}}" style="width:150px; height:30px">
    </div>

    <div>
      <label>Bond</label><br>
      <%= collection_select :transact, :bond_id, Bond.order(:ticker), :id, :print_description, {include_blank: true, class: "form-control", selected: ''}, {style:"width:150px; height:30px"}%>
    </div>
    <br>
    <div class="form-group">
      <label for="transact_price">Price</label><br>
      <input class="form-control" step="0.001" type="number" name="transact[price]" id="transact_price" value="{{price}}" style="width:150px; height:30px">
    </div>

    <div class="form-group">
      <label>Trader</label><br>
      <%= collection_select :transact, :trader_id, Trader.order(:name), :id, :name, {include_blank: true, class: "form-control", selected: ''}, {style:"width:150px; height:30px"} %>
    </div>
    <p>{{trader_id}}</p>
    <div>
      <label>Client</label><br>
      <%= collection_select :transact, :client_id, Client.order(:name), :id, :name, {include_blank: true, class: "form-control", selected: ''}, {style:"width:150px; height:30px"} %>
    </div>

    <div class="form-group">
        <label>Salespeople</label><br>
        <%= collection_select :transact, :salesperson_ids, Salesperson.order(:name), :id, :name, {include_blank: true, class: "form-control", selected: select_salesperson}, {multiple: true, style:"width:150px; height:100px"} %>
    </div>

    <div class="form-group">
        <label for="transact_Time of trade">Time of trade</label><br>
        <input value="{{trade_time}}" type="datetime-local" name="transact[trade_time]" id="transact_trade_time">
    </div>

    <input value="false" type="hidden" name="transact[pending]" id="transact_pending">
    <input value="true" type="hidden" name="no_reload">
    <div class="actions">
    <input type="submit" name="commit" value="Book Trade" class="btn btn-primary" data-disable-with="Create Transact">
    </div>
</form>
</div>
</script>