config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/transacts/new', to: 'transacts#new'
  # get '/transacts/:id', to: 'transacts#show', as: 'transact'
  # get '/transacts', to: 'transacts#index'
  # post '/transacts', to: 'transacts#create'

  resources :transacts
  resources :traders, only: [:show, :index]
  resources :salespeople, only: [:show, :index]
  resources :clients, only: [:show, :index]
  resources :bonds, only: [:show, :index]
  resources :users, only: [:new, :create, :update]

  get '/home', to: 'users#home', as: 'home'
  get 'signup', to: 'users#new'

  get '/auth/github/callback' => 'sessions#create'

  get '/users/new_fb', to: 'users#new_fb'

  patch '/transacts/:id/confirm', to: 'transacts#confirm', as: 'confirm_transact'
  get '/pending_transacts', to: 'transacts#pending'

  get '/signin', to: 'sessions#new', as: 'signin'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions/', to: 'sessions#destroy'

  root 'users#home'

  resources :traders, only: [:show] do
  	resources :transacts, only: [:show, :index]
    resources :bonds, only: [:index]
    get '/pending_transacts', to: 'transacts#pending'
  end

  resources :clients, only: [:show] do
    resources :transacts, only: [:show, :index, :new, :create]
  end

  resources :bonds, only: [:show] do
    resources :transacts, only: [:show, :index, :new, :create]
  end

  resources :salespeople, only: [:show] do
    resources :transacts, only: [:show, :index]
    get '/pending_transacts', to: 'transacts#pending'
  end

end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
	
	validates_presence_of :name, :username, :user_type
	validates :username, uniqueness: true

	def self.find_or_create_by_omniauth(auth_hash)
	  username = auth_hash['info']['username']
      	where(:username => username).first_or_create do |user|
	        user.name = auth_hash['info']['name']
	        user.uid = auth_hash['uid']
	  	end
	end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]
  def new
    redirect_to home_path unless !current_user
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      session[:user_id] = @user.id
      if @user.user_type == "Trader"
        Trader.create(trader_params)
        session[:type] = "Trader"
        redirect_to home_path
      elsif @user.user_type == "Salesperson"
        Salesperson.create(salesperson_params)
        session[:type] = "Salesperson"
        redirect_to home_path
      end
    else
      render :new
    end
  end


  def home
    @user = current_user
    if @user.user_type == "Trader"
      @trader = Trader.find_by(username: @user.username)
      @transacts = Transact.where(trader_id: @trader.id).not_pending
    elsif @user.user_type == "Salesperson"
      @salesperson = Salesperson.find_by(username: @user.username)
      @transacts = Transact.joins(:salesperson_transacts).where(salesperson_transacts: {salesperson_id: @salesperson.id}).not_pending
    end
  end

  def new_fb
  end

  def update
    @user.update(user_params)
  end



  private
  def trader_params
    params.require(:user).permit(
      :name,
      :username
      )
  end
  def salesperson_params
    params.require(:user).permit(
      :name,
      :username
      )
  end

  def user_params
    params.require(:user).permit(
      :name,
      :username,
      :password,
      :user_type,
      :uid)
  end


end

app/views/users/_form.html.erb
<% if @user.uid %>
<p>Please fill out the following information to complete your registration with GitHub</p>
<% end %>


<div class="col-sm-6">
<%= form_for @user do |f| %>
   <div class="form-group">
    <%= f.label :username %>
    <br>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "Display Name" %>
    <br>
    <%= f.text_field :name, class: "form-control", value: @user.name %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <br>
    <%= f.password_field :password, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "I am a:" %><br>
    <%= f.select :user_type, ["Trader", "Salesperson"], {class: "form-control"} %>
  </div>

  <% if @user.uid %>
    <%= f.hidden_field :uid, value: @user.uid %>
  <% end %>
  <div class="actions">
    <br/>
    <%= f.submit class: "btn btn-primary" %>
  </div>


<% end %>
</div>

app/views/users/home.html.erb
<h1>Welcome, <%= @user.name %></h1>
<span class="col-sm-4" align="center"><h4><%= link_to "Book New Trade", new_transact_path %></h4></span>
<% if @trader %>
	
	<span class="col-sm-4" align="center"><h4><%= link_to "My Completed Trades", trader_transacts_path(@trader) %></h4></span>
	<span class="col-sm-4" align="center"><h4><%= link_to "My Pending Trades", trader_pending_transacts_path(@trader) %></h4></span>	

<% elsif @salesperson %>
	
	<span class="col-sm-4" align="center"><h4><%= link_to "My Completed Trades", salesperson_transacts_path(@salesperson) %></h4></span>
	<span class="col-sm-4" align="center"><h4><%= link_to "My Pending Trades", salesperson_pending_transacts_path(@salesperson) %></h4></span>	

<% end %>
<br><br><br>
<%= render 'templates/show' %>

app/views/users/new.html.erb
<%= render 'users/form' %>

app/views/users/new_fb.html.erb
<% binding.pry %>
<%= form_for @user do |f| %>

   <div class="form-group">
    <%= f.label :name %>
    <br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
   <div class="form-group">
    <%= f.label :username %>
    <br>
    <%= f.text_field :username, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label "I am a:" %><br>
    <%= f.select :user_type, ["Trader", "Salesperson"], {class: "form-control"} %>
  </div>

  <div class="actions">
    <br/>
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>