config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/transacts/new', to: 'transacts#new'
  # get '/transacts/:id', to: 'transacts#show', as: 'transact'
  # get '/transacts', to: 'transacts#index'
  # post '/transacts', to: 'transacts#create'

  resources :transacts
  resources :traders, only: [:show, :index]
  resources :salespeople, only: [:show, :index]
  resources :clients, only: [:show, :index]
  resources :bonds, only: [:show, :index]
  resources :users, only: [:new, :create, :update]

  get '/home', to: 'users#home', as: 'home'
  get 'signup', to: 'users#new'

  get '/auth/github/callback' => 'sessions#create'

  get '/users/new_fb', to: 'users#new_fb'

  patch '/transacts/:id/confirm', to: 'transacts#confirm', as: 'confirm_transact'
  get '/pending_transacts', to: 'transacts#pending'

  get '/signin', to: 'sessions#new', as: 'signin'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions/', to: 'sessions#destroy'

  root 'users#home'

  resources :traders, only: [:show] do
  	resources :transacts, only: [:show, :index]
    resources :bonds, only: [:index]
    get '/pending_transacts', to: 'transacts#pending'
  end

  resources :clients, only: [:show] do
    resources :transacts, only: [:show, :index, :new, :create]
  end

  resources :bonds, only: [:show] do
    resources :transacts, only: [:show, :index, :new, :create]
  end

  resources :salespeople, only: [:show] do
    resources :transacts, only: [:show, :index]
    get '/pending_transacts', to: 'transacts#pending'
  end

end

app/models/client.rb
class Client < ApplicationRecord
	validates :name, uniqueness: true

	has_many :transacts
	has_many :bonds, through: :transacts
	has_many :traders, through: :transacts
	has_many :salespeople, through: :transacts
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController

	before_action :current_client, only: [:show]
  # def new
  # 	@client = Client.new
  # end

  # def create
  #   client = Client.create(client_params)
  #   redirect_to client_path(client)
  # end

  def show
  	@transacts = Transact.where(client_id: params[:id]).not_pending
    respond_to do |format|
      format.html {render :show}
      format.json {render json: @client}
    end
  end

  def index
  	@items = Client.all
  end

  # def update
  # 	@client.update(client_params)
  # 	redirect_to client_path(@client)
  # end

  private

  # def client_params
  #   params.require(:client).permit(
  #     :name
  #     )
  # end

  def current_client
  	@client = Client.find_by(id: params[:id])
  end
end

app/views/clients/index.html.erb
<%= render 'templates/index', collection: @items %>

app/views/clients/show.html.erb
<span><h1><%= @client.name %></h1></span>
	<span class="col-sm-4"><%= link_to "Book a new trade", new_client_transact_path(@client) %></span><br>
<p><button id="client-recent-js" data-id="<%= @client.id %>">Recent Activity</button></p>
<div id="client-recent-transacts"></div>
	<% if !@transacts.empty? %>
		<span class="col-sm-3"><h4>View trade history:</h4></span>
		<span class="col-sm-3" ><h5><%= link_to "Past Month", client_transacts_path(@client, period: "one_month") %></h5></span>
		<span class="col-sm-3" ><h5><%= link_to "Past Quarter", client_transacts_path(@client, period: "one_quarter") %></h5></span>
		<span class="col-sm-3" ><h5><%= link_to "All time", client_transacts_path(@client) %></h5></span>
	<% end %>
<br>
<%= render 'templates/show' %>

<script id="display-client-trades-template" type="text/x-handlebars-template">
	<table class='table table-borderless' id="js-display-trades-header">
		<caption>Recent Trades</caption>
		<thead>
			<tr>
				<td>Type</td>
				<td>Size</td>
				<td>Bond</td>
				<td>Price</td>
			</tr>
		</thead>
		<tbody>
	    {{#each this}}
	        <tr>            
	            <td>{{trade_type}}</td>
	            <td>{{size}}</td>
	            <td>{{bond.description}}</td>
	            <td>{{price}}</td>
	        </tr>
	    {{/each}}
		</tbody>
	</table>
</script>