config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # get '/transacts/new', to: 'transacts#new'
  # get '/transacts/:id', to: 'transacts#show', as: 'transact'
  # get '/transacts', to: 'transacts#index'
  # post '/transacts', to: 'transacts#create'

  resources :transacts
  resources :traders, only: [:show, :index]
  resources :salespeople, only: [:show, :index]
  resources :clients, only: [:show, :index]
  resources :bonds, only: [:show, :index]
  resources :users, only: [:new, :create, :update]

  get '/home', to: 'users#home', as: 'home'
  get 'signup', to: 'users#new'

  get '/auth/github/callback' => 'sessions#create'

  get '/users/new_fb', to: 'users#new_fb'

  patch '/transacts/:id/confirm', to: 'transacts#confirm', as: 'confirm_transact'
  get '/pending_transacts', to: 'transacts#pending'

  get '/signin', to: 'sessions#new', as: 'signin'
  post '/sessions', to: 'sessions#create', as: 'sessions'
  delete '/sessions/', to: 'sessions#destroy'

  root 'users#home'

  resources :traders, only: [:show] do
  	resources :transacts, only: [:show, :index]
    resources :bonds, only: [:index]
    get '/pending_transacts', to: 'transacts#pending'
  end

  resources :clients, only: [:show] do
    resources :transacts, only: [:show, :index, :new, :create]
  end

  resources :bonds, only: [:show] do
    resources :transacts, only: [:show, :index, :new, :create]
  end

  resources :salespeople, only: [:show] do
    resources :transacts, only: [:show, :index]
    get '/pending_transacts', to: 'transacts#pending'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bond Desk</title>

    <%= csrf_meta_tags %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'style', media: 'all' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
     
  </head>
  <body>
    <div class="navbar navbar-inverse navbar-static-top" role="navigation">
      <div class="container-fluid">
        <div class="navbar-header">
        
        <% if !current_user %>
          <a class="navbar-brand" href="<%= new_user_path %>"/>Sign Up</a>
          <%= link_to "Log in", signin_path, class:"navbar-brand" %>
        <% end %>
        <% if current_user %>
        <a class="navbar-brand" href="<%= home_path %>"/>Home</a>
        <%= link_to "Bonds", bonds_path, class: "navbar-brand" %>
        <%= link_to "Trades", transacts_path, class: "navbar-brand" %>
        <%= link_to "Clients", clients_path, class: "navbar-brand" %>
        <%= link_to "Traders", traders_path, class: "navbar-brand" %>
        <%= link_to "Salespeople", salespeople_path, class: "navbar-brand" %>
        <%= link_to "Log Out", sessions_path, class:"navbar-brand",method:'delete' %>
        <% end %>
        </div>
      </div>
    </div>

    <!-- content -->
      <div class="container"  role="main">
        <%= yield %>
      </div>
  </body>
</html>